const actionTypes = {
    ON_ERROR: 'ON_ERROR',
    ON_SET_MEDIA: 'ON_SET_MEDIA',
    ON_REMOVE_FROM_CART: 'ON_REMOVE_FROM_CART',
    ON_ADD_TO_CART: 'ON_ADD_TO_CART',
    ON_SET_DATA: 'ON_SET_DATA',
    // ON_CREATE_NOTIFICATION: 'ON_CREATE_NOTIFICATION'
};

export default actionTypes;