const actionTypes = {
    ON_ADD_TO_FAVORITES: 'ON_ADD_TO_FAVORITES',
    ON_ERROR: 'ON_ERROR',
    ON_SET_MEDIA: 'ON_SET_MEDIA',
    ON_REMOVE_FROM_CART: 'ON_REMOVE_FROM_CART',
    ON_ADD_TO_CART: 'ON_ADD_TO_CART',
    ON_SET_DATA: 'ON_SET_DATA'
};

export default actionTypes;